# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plot_builder.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import matplotlib.pyplot as plt
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure

from numpy import random



from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_LEFT = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_LEFT.sizePolicy().hasHeightForWidth())
        self.frame_LEFT.setSizePolicy(sizePolicy)
        self.frame_LEFT.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_LEFT.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_LEFT.setObjectName("frame_LEFT")
        self.frame_L_Axes = QtWidgets.QFrame(self.frame_LEFT)
        self.frame_L_Axes.setGeometry(QtCore.QRect(8, 8, 80, 34))
        self.frame_L_Axes.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_L_Axes.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_L_Axes.setObjectName("frame_L_Axes")
        self.label_L_Axes = QtWidgets.QLabel(self.frame_L_Axes)
        self.label_L_Axes.setGeometry(QtCore.QRect(8, 8, 64, 18))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_L_Axes.sizePolicy().hasHeightForWidth())
        self.label_L_Axes.setSizePolicy(sizePolicy)
        self.label_L_Axes.setObjectName("label_L_Axes")
        self.horizontalLayout.addWidget(self.frame_LEFT)
        self.frame_RIGHT = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_RIGHT.sizePolicy().hasHeightForWidth())
        self.frame_RIGHT.setSizePolicy(sizePolicy)
        self.frame_RIGHT.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_RIGHT.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_RIGHT.setObjectName("frame_RIGHT")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_RIGHT)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_R_SQL = QtWidgets.QFrame(self.frame_RIGHT)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_R_SQL.sizePolicy().hasHeightForWidth())
        self.frame_R_SQL.setSizePolicy(sizePolicy)
        self.frame_R_SQL.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_R_SQL.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_R_SQL.setObjectName("frame_R_SQL")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_R_SQL)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_RS_Text = QtWidgets.QFrame(self.frame_R_SQL)
        self.frame_RS_Text.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_RS_Text.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_RS_Text.setObjectName("frame_RS_Text")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_RS_Text)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_R_S_Button = QtWidgets.QFrame(self.frame_RS_Text)
        self.frame_R_S_Button.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_R_S_Button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_R_S_Button.setObjectName("frame_R_S_Button")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_R_S_Button)
        self.textBrowser.setGeometry(QtCore.QRect(10, 10, 331, 191))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setMinimumSize(QtCore.QSize(0, 100))
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_2.addWidget(self.frame_R_S_Button)
        self.pushButton = QtWidgets.QPushButton(self.frame_RS_Text, clicked = lambda: self.plotOnCanvas())
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0,200,96);\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    color: rgb(205, 230, 255);\n"
"    font: 75 14pt \"Arial\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(0,240,115);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0,200,96);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.horizontalLayout_3.addWidget(self.frame_RS_Text)
        self.verticalLayout_2.addWidget(self.frame_R_SQL)
        self.frame_R_Plot = QtWidgets.QFrame(self.frame_RIGHT)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_R_Plot.sizePolicy().hasHeightForWidth())
        self.frame_R_Plot.setSizePolicy(sizePolicy)
        self.frame_R_Plot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_R_Plot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_R_Plot.setObjectName("frame_R_Plot")

        # create a horizontal layout for a plot
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_R_Plot)
        self.horizontalLayout_4.setObjectName("horizontalLayout_Plot")
        ## Canvas here
        self.figure = plt.figure()
        self.canvas = FigureCanvas(self.figure)
        ## end of Canvas
        ## add a canvas
        self.horizontalLayout_4.addWidget(self.canvas)
        # end of horizontal layout for a plot adding

        self.verticalLayout_2.addWidget(self.frame_R_Plot)
        self.horizontalLayout.addWidget(self.frame_RIGHT)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_L_Axes.setText(_translate("MainWindow", "X & Y Axes"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">SELECT * FROM \'ak98_events\'</p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Execute Request"))

    # ----------------------------------------------------------------------------
    def plotOnCanvas(self):
        ## clear the canvas
        self.figure.clear()

        #
        fruits = [ 'apples', 'orages', 'coca', "pie" ]
        values = random.randint(50,size=(4))
        print(values)

        # create the bar plot
        plt.bar(fruits, values, color = "green", width = 0.25)
        plt.xlabel = "Type of Fruits"
        plt.ylabel = "No. of fruits"
        plt.title = "Fruits in my basket"

        #draw and refresh the canvas
        self.canvas.draw()


if __name__ == "__main__":

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
